repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0     # <— pin back
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        args: ["--maxkb=5000"]

  # (Optional, later) Add Python formatters/linters when ready:
  # - repo: https://github.com/psf/black
  #   rev: 24.8.0
  #   hooks:
  #     - id: black
  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.6.3
  #   hooks:
  #     - id: ruff
  #     - id: ruff-format
