repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer         # ensures file ends with a single newline
      - id: trailing-whitespace       # removes stray trailing spaces
      - id: mixed-line-ending         # fixes CRLF/LF inconsistencies
        args: [--fix=lf]
      - id: check-yaml                # validates YAML syntax
      - id: check-toml                # validates TOML syntax
      - id: check-added-large-files   # prevents accidentally committing huge files
        args: ["--maxkb=5000"]        # ~5 MB

  # (Optional, later) Add Python formatters/linters when ready:
  # - repo: https://github.com/psf/black
  #   rev: 24.8.0
  #   hooks:
  #     - id: black
  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.6.3
  #   hooks:
  #     - id: ruff
  #     - id: ruff-format
